version: "1.0"
stages:
  - "clone"
  - "build"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "sushant08/cf-java"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  build:
    title: Packaging Jar file
    stage: build
    image: gradle:4.10.0-jdk8-alpine
    commands:
     - gradlew -Dorg.gradle.daemon=false test
     - gradlew -g gradle-user-home -Dorg.gradle.daemon=false build jacocoTestReport
  