version: "1.0"
fail_fast: false
stages:
  - "clone"
  - "infra_build"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "sushant08/cf-java"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  DeployWithTerraform:
    image: hashicorp/terraform:0.12.0
    title: Deploying Terraform plan
    stage: infra_build
    commands:
      - terraform init infrasturcture
      - terraform apply -auto-approve infrasturcture



  