version: "1.0"
fail_fast: false
stages:
  - "clone"
  - "build"
  - "infra_build"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "sushant08/cf-java"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  build:
    title: Packaging Jar file
    stage: build
    image: gradle:4.10.0-jdk8-alpine
    commands:
     - gradlew -Dorg.gradle.daemon=false test  
  DeployWithTerraform:
    image: hashicorp/terraform:0.12.0
    title: Deploying Terraform plan
    stage: infra_build
    commands:
      - terraform init infrasturcture
      - terraform apply -auto-approve infrasturcture



  