version: "1.0"
fail_fast: false
stages:
  - "clone"
  - "infra_build"
  - "notify"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "sushant08/cf-java"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  DeployWithTerraform:
    image: hashicorp/terraform:0.12.0
    title: Deploying Terraform plan
    stage: infra_build
    commands:
      - terraform init infrasturcture
      - terraform plan infrasturcture
  SendToSlack:
    title: notifySlack
    stage: notify
    image: 'codefreshplugins/slack-message-sender:0.1'
    commands:
      - slack-message-sender send --webhook-url https://hooks.slack.com/services/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 --message "My Test message"



  